@startuml

hide footbox

Créateur -> Gestionnaire : Flux 2 - **RechercheCercleSoins -**<font color=red> GET [Lien vers le serveur] / [CareTeam] { ?[parameters]{&_format=[mime-type]} }

Gestionnaire --> Créateur : Flux 3  - **ResultatRechercheCercleSoins -** <font color=red> HTTP 200 OK + {Bundle:CareTeam}

@enduml