@startuml

hide footbox

Créateur -> Gestionnaire : PCC-45  Flux 1 - **CreationCercleSoins** - <font color=red> POST [Lien vers le serveur] / CareTeam
Gestionnaire --> Créateur : <font color=red> HTTP 201 created

Créateur -> Gestionnaire : PCC-46 Flux 2 - **RechercheCercleSoins -**<font color=red> GET [Lien vers le serveur] / [CareTeam]/_search
Gestionnaire --> Créateur : Flux 3  - **ResultatRechercheCercleSoins -** <font color=red> HTTP 200 OK + {Bundle: CareTeam}

Créateur -> Gestionnaire : PCC-47  Flux 2bis - **RecuperationCercleSoins** - <font color=red> GET [Lien vers le serveur] / CareTeam/[id]
Gestionnaire --> Créateur : Flux 3bis  - **ResultatRecuperationCercleSoins -**  <font color=red> HTTP 200 OK + {CareTeam}

Créateur -> Gestionnaire : PCC-45 Flux 4 - **MiseJourCercleSoins** - <font color=red> PUT  [Lien vers le serveur] /CareTeam/ [id]
Gestionnaire --> Créateur : <font color=red> HTTP 200 OK

@enduml