@startuml

skinparam backgroundColor #fcf6eb
skinparam activityBackgroundColor #efd9fc
skinparam activityBorderColor #000000
skinparam shadowing false
skinparam defaultFontSize 12

|Créateur|
start
:Saisir le cercle de soins;
:Envoyer la demande;
-[dashed]-> flux 1 - **CreationCercleSoins**;
|Gestionnaire|
:Créer le cercle de soin;
stop 
@enduml