@startuml

hide footbox

Créateur -> Gestionnaire : [[spe_creation_cercle_soins.html#interaction-transaction Flux 1c - CreationCercleSoinsTransaction]] \n POST [Lien vers le serveur]/
Gestionnaire --> Créateur : HTTP 201 created
@enduml