@startuml

hide footbox 

Consommateur -> Gestionnaire : [[spe_consultation_cercle_soins.html#recherche-et-récupération-du-cercle-de-soins Flux 2b - RecuperationCercleSoins]] \n GET [Lien vers le serveur] / [CareTeam] / [id]
Gestionnaire --> Consommateur : [[spe_consultation_cercle_soins.html#recherche-et-récupération-du-cercle-de-soins Flux 3b - ResultatRecuperationCercleSoins]] \n HTTP 200 OK + {CareTeam}

@enduml
