@startuml

hide footbox

Créateur -> Gestionnaire : [[spe_creation_cercle_soins.html#gestion-du-cercle-de-soins Flux 1b - CreationCercleSoinsRESTful]] \n POST [Lien vers le serveur] / [CareTeam]
Gestionnaire --> Créateur : HTTP 201 created
@enduml