# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cds
canonical: https://interop.esante.gouv.fr/ig/fhir/cds 
name: CDS
title: Cercle De Soins
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: active
version: 2.0.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
# releaseLabel: trial-use
releaseLabel: final-text

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

dependencies:
  ans.fhir.fr.annuaire: 1.1.0
  hl7.fhir.fr.core: 2.1.0
  ans.fr.terminologies: latest
  hl7.fhir.uv.extensions.r4: 5.2.0
  ans.fr.mos: 0.1.0-ballot

parameters:
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en



pages:
    index.md:
        title: Accueil
    specifications.md: 
        spe_synthese.md:
            title: Synthèse
        spe_creation_cercle_soins.md:
            title: Création du cercle de soins
        spe_consultation_cercle_soins.md:
            title: Consultation du cercle de soins
        spe_mise_jour_cercle_soins.md:
            title: Mise à jour du cercle de soins
    tests.md: 
        title: Tests
    annexes.md:
        title: Annexes
        downloads.md:
            title: Téléchargements et usages
        translationinfo.md:
            title: Informations sur la traduction
    changes.md:
        title: Historique


menu:
    Accueil: index.html
    Spécifications:
        Synthèse: spe_synthese.html
        Création du cercle de soins: spe_creation_cercle_soins.html
        Consultation du cercle de soins: spe_consultation_cercle_soins.html
        Mise à jour du cercle de soins: spe_mise_jour_cercle_soins.html
    Ressources de conformité: artifacts.html
    Tests: tests.html
    Annexes: 
        Informations sur la traduction: translationinfo.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: changes.html

