# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cds
canonical: https://interop.esante.gouv.fr/ig/fhir/cds 
name: CDS
title: Cercle De Soins
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: active
version: 2.0.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
# releaseLabel: trial-use
releaseLabel: final-text

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

dependencies:
  ans.fhir.fr.annuaire: 1.1.0
  hl7.fhir.fr.core: 2.1.0
  ans.fr.terminologies: latest
  hl7.fhir.uv.extensions.r4: 5.2.0

parameters:
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Volume 1 - Etude fonctionnelle
    specifications_techniques.md:
        interaction_restful.md:
            title: Interactions RESTful
        interaction_transaction.md:
            title: Interactions transaction
        recherche_recuperation_cds.md:
            title: Recherche CDS
        correspondances_metier.md:
            title: Correspondances métier
    annexes.md:
        title: Annexes
        normes_standards.md: 
            title: Normes et standards
        normes_standards_ig_annexe.md:
            title: IG N&S
        downloads.md:
            title: Téléchargements et usages
    changes.md:
        title: Historique


menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Interactions RESTful: interaction_restful.html
        Interactions transaction: interaction_transaction.html
        Recherche CDS: recherche_recuperation_cds.html
        Correspondances métier: correspondances_metier.html
    Ressources de conformité: artifacts.html
    Annexes:
        Normes et standards: normes_standards.html
        IG N&S: normes_standards_ig_annexe.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: changes.html